version: '3'
services:
  db:
    image: mongo:latest
    container_name: gateways-manager-db
    restart: always
    volumes:
      - gateways-manager-db-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - gateways_manager_app_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: gateways-manager-api
    depends_on:
      - db
    restart: always
    ports:
      - 4004:4004
    environment:
      - MONGO_DB_URL=mongodb://root:root@db:27017/?retryWrites=true&w=majority
    networks:
      - gateways_manager_app_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: gateways-manager-client
    depends_on:
      - api
    restart: always
    ports:
      - 8000:80
    networks:
      - gateways_manager_app_network
    
networks:
  gateways_manager_app_network:
    driver: bridge

volumes:
  gateways-manager-db-volume: